+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n '' ']'
+ trap POST_TEST_DEFAULT EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Wed Apr  5 17:14:19 2023 - INFO  - Start testing...
+ dmidecode -h
+ grep -i 'Usage: dmidecode'
oe_test_dmidecode.sh: line 25: dmidecode: command not found
+ CHECK_RESULT 1 0 0 'dmidecode -h fail'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='dmidecode -h fail'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'dmidecode -h fail'
+ LOG_ERROR 'dmidecode -h fail'
+ message='dmidecode -h fail'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'dmidecode -h fail'
Wed Apr  5 17:14:20 2023 - ERROR - dmidecode -h fail
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dmidecode.sh line 26'
+ message='oe_test_dmidecode.sh line 26'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dmidecode.sh line 26'
Wed Apr  5 17:14:21 2023 - ERROR - oe_test_dmidecode.sh line 26
+ '[' 0 -eq 1 ']'
+ return 0
+ dmidecode -t system
+ grep -i 'Getting SMBIOS data from sysfs'
oe_test_dmidecode.sh: line 27: dmidecode: command not found
+ CHECK_RESULT 1 0 0 'dmidecode -t system fail'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='dmidecode -t system fail'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'dmidecode -t system fail'
+ LOG_ERROR 'dmidecode -t system fail'
+ message='dmidecode -t system fail'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'dmidecode -t system fail'
Wed Apr  5 17:14:22 2023 - ERROR - dmidecode -t system fail
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dmidecode.sh line 28'
+ message='oe_test_dmidecode.sh line 28'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dmidecode.sh line 28'
Wed Apr  5 17:14:23 2023 - ERROR - oe_test_dmidecode.sh line 28
+ '[' 0 -eq 1 ']'
+ return 0
+ dmidecode -t bios
+ grep -i 'Getting SMBIOS data from sysfs'
oe_test_dmidecode.sh: line 29: dmidecode: command not found
+ CHECK_RESULT 1 0 0 'dmidecode -t bios fail'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='dmidecode -t bios fail'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'dmidecode -t bios fail'
+ LOG_ERROR 'dmidecode -t bios fail'
+ message='dmidecode -t bios fail'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'dmidecode -t bios fail'
Wed Apr  5 17:14:24 2023 - ERROR - dmidecode -t bios fail
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dmidecode.sh line 30'
+ message='oe_test_dmidecode.sh line 30'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dmidecode.sh line 30'
Wed Apr  5 17:14:25 2023 - ERROR - oe_test_dmidecode.sh line 30
+ '[' 0 -eq 1 ']'
+ return 0
+ dmidecode -t baseboard
+ grep -i 'Getting SMBIOS data from sysfs'
oe_test_dmidecode.sh: line 31: dmidecode: command not found
+ CHECK_RESULT 1 0 0 'dmidecode -t baseboard fail'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='dmidecode -t baseboard fail'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'dmidecode -t baseboard fail'
+ LOG_ERROR 'dmidecode -t baseboard fail'
+ message='dmidecode -t baseboard fail'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'dmidecode -t baseboard fail'
Wed Apr  5 17:14:26 2023 - ERROR - dmidecode -t baseboard fail
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dmidecode.sh line 32'
+ message='oe_test_dmidecode.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dmidecode.sh line 32'
Wed Apr  5 17:14:27 2023 - ERROR - oe_test_dmidecode.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ dmidecode -t chassis
+ grep -i 'Getting SMBIOS data from sysfs'
oe_test_dmidecode.sh: line 33: dmidecode: command not found
+ CHECK_RESULT 1 0 0 'dmidecode -t chassis fail'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='dmidecode -t chassis fail'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'dmidecode -t chassis fail'
+ LOG_ERROR 'dmidecode -t chassis fail'
+ message='dmidecode -t chassis fail'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'dmidecode -t chassis fail'
Wed Apr  5 17:14:29 2023 - ERROR - dmidecode -t chassis fail
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dmidecode.sh line 34'
+ message='oe_test_dmidecode.sh line 34'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dmidecode.sh line 34'
Wed Apr  5 17:14:30 2023 - ERROR - oe_test_dmidecode.sh line 34
+ '[' 0 -eq 1 ']'
+ return 0
+ dmidecode -t processor
+ grep -i 'Getting SMBIOS data from sysfs'
oe_test_dmidecode.sh: line 35: dmidecode: command not found
+ CHECK_RESULT 1 0 0 'dmidecode -t processor fail'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='dmidecode -t processor fail'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'dmidecode -t processor fail'
+ LOG_ERROR 'dmidecode -t processor fail'
+ message='dmidecode -t processor fail'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'dmidecode -t processor fail'
Wed Apr  5 17:14:31 2023 - ERROR - dmidecode -t processor fail
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dmidecode.sh line 36'
+ message='oe_test_dmidecode.sh line 36'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dmidecode.sh line 36'
Wed Apr  5 17:14:31 2023 - ERROR - oe_test_dmidecode.sh line 36
+ '[' 0 -eq 1 ']'
+ return 0
+ dmidecode -t memory
+ grep -i 'Getting SMBIOS data from sysfs'
oe_test_dmidecode.sh: line 37: dmidecode: command not found
+ CHECK_RESULT 1 0 0 'dmidecode -t memory fail'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='dmidecode -t memory fail'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'dmidecode -t memory fail'
+ LOG_ERROR 'dmidecode -t memory fail'
+ message='dmidecode -t memory fail'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'dmidecode -t memory fail'
Wed Apr  5 17:14:32 2023 - ERROR - dmidecode -t memory fail
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dmidecode.sh line 38'
+ message='oe_test_dmidecode.sh line 38'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dmidecode.sh line 38'
Wed Apr  5 17:14:33 2023 - ERROR - oe_test_dmidecode.sh line 38
+ '[' 0 -eq 1 ']'
+ return 0
+ dmidecode -t cache
+ grep -i 'Getting SMBIOS data from sysfs'
oe_test_dmidecode.sh: line 39: dmidecode: command not found
+ CHECK_RESULT 1 0 0 'dmidecode -t cache fail'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='dmidecode -t cache fail'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'dmidecode -t cache fail'
+ LOG_ERROR 'dmidecode -t cache fail'
+ message='dmidecode -t cache fail'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'dmidecode -t cache fail'
Wed Apr  5 17:14:34 2023 - ERROR - dmidecode -t cache fail
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_dmidecode.sh line 40'
+ message='oe_test_dmidecode.sh line 40'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_dmidecode.sh line 40'
Wed Apr  5 17:14:35 2023 - ERROR - oe_test_dmidecode.sh line 40
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Wed Apr  5 17:14:36 2023 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 8
+ test 8 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Apr  5 17:14:37 2023 - ERROR - failed to execute the case.
+ exit 8
+ POST_TEST_DEFAULT
+ LOG_INFO 'oe_test_dmidecode.sh post_test'
+ message='oe_test_dmidecode.sh post_test'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'oe_test_dmidecode.sh post_test'
Wed Apr  5 17:14:38 2023 - INFO  - oe_test_dmidecode.sh post_test
