+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Wed Apr  5 12:41:27 2023 - INFO  - Start environmental preparation.
+ DNF_INSTALL 'cobbler httpd'
+ pkgs='cobbler httpd'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'cobbler httpd' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmp4l2l_diw
+ '[' -z '' ']'
+ tmpfile=/tmp/tmp4l2l_diw
+ mount /dev/cdrom /mnt
mount: /mnt: special device /dev/cdrom does not exist.
+ systemctl start httpd
+ systemctl start cobblerd
+ cobbler distro add --name=OpenEuler --owners=root --boot-loader=grub --initrd=/mnt/images/pxeboot/initrd.img --kernel=/mnt/isolinux/vmlinuz
cobblerd does not appear to be running/accessible: ConnectionRefusedError(111, 'Connection refused')
Traceback (most recent call last):
  File "/usr/bin/cobbler", line 35, in <module>
    sys.exit(app.main())
  File "/usr/lib/python3.10/site-packages/cobbler/cli.py", line 852, in main
    rc = cli.run(sys.argv)
  File "/usr/lib/python3.10/site-packages/cobbler/cli.py", line 418, in run
    self.token = self.remote.login("", self.shared_secret)
  File "/usr/lib64/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib64/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.10/xmlrpc/client.py", line 1196, in single_request
    raise ProtocolError(
xmlrpc.client.ProtocolError: <ProtocolError for 127.0.0.1:80/cobbler_api: 503 Service Unavailable>
+ cobbler profile add --name=OpenEuler --distro=OpenEuler
cobblerd does not appear to be running/accessible: ConnectionRefusedError(111, 'Connection refused')
Traceback (most recent call last):
  File "/usr/bin/cobbler", line 35, in <module>
    sys.exit(app.main())
  File "/usr/lib/python3.10/site-packages/cobbler/cli.py", line 852, in main
    rc = cli.run(sys.argv)
  File "/usr/lib/python3.10/site-packages/cobbler/cli.py", line 418, in run
    self.token = self.remote.login("", self.shared_secret)
  File "/usr/lib64/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib64/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.10/xmlrpc/client.py", line 1196, in single_request
    raise ProtocolError(
xmlrpc.client.ProtocolError: <ProtocolError for 127.0.0.1:80/cobbler_api: 503 Service Unavailable>
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Wed Apr  5 12:44:36 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run testcase.'
+ message='Start to run testcase.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run testcase.'
Wed Apr  5 12:44:38 2023 - INFO  - Start to run testcase.
+ cobbler system add --name=OpenEuler1 --profile=OpenEuler
exception on server: 'invalid profile name: OpenEuler'
+ CHECK_RESULT 0 0 0 'Failed option: system add'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed option: system add'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ cobbler system copy --name=OpenEuler1 --newname=OpenEuler2
exception on server: 'internal error, unknown system name OpenEuler1'
+ CHECK_RESULT 0 0 0 'Failed option: system copy'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed option: system copy'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ cobbler system list
+ grep OpenEuler2
+ CHECK_RESULT 1 0 0 'Failed option: sysetm copy'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed option: sysetm copy'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed option: sysetm copy'
+ LOG_ERROR 'Failed option: sysetm copy'
+ message='Failed option: sysetm copy'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed option: sysetm copy'
Wed Apr  5 12:44:59 2023 - ERROR - Failed option: sysetm copy
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_cobbler_system.sh line 40'
+ message='oe_test_cobbler_system.sh line 40'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_cobbler_system.sh line 40'
Wed Apr  5 12:45:00 2023 - ERROR - oe_test_cobbler_system.sh line 40
+ '[' 0 -eq 1 ']'
+ return 0
+ cobbler system dumpvars --name=OpenEuler1
+ grep allow_duplicate_hostnames
+ CHECK_RESULT 1 0 0 'Failed option: system dumpvars'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed option: system dumpvars'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed option: system dumpvars'
+ LOG_ERROR 'Failed option: system dumpvars'
+ message='Failed option: system dumpvars'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed option: system dumpvars'
Wed Apr  5 12:45:08 2023 - ERROR - Failed option: system dumpvars
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_cobbler_system.sh line 42'
+ message='oe_test_cobbler_system.sh line 42'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_cobbler_system.sh line 42'
Wed Apr  5 12:45:09 2023 - ERROR - oe_test_cobbler_system.sh line 42
+ '[' 0 -eq 1 ']'
+ return 0
+ cobbler system edit --name=openEuler1 --owners=tom
exception on server: 'internal error, unknown system name openEuler1'
+ CHECK_RESULT 0 0 0 'Failed option: system edit'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed option: system edit'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ cobbler system report --name=openEuler1
+ grep tom
+ CHECK_RESULT 1 0 0 'Failed option: system edit'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed option: system edit'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed option: system edit'
+ LOG_ERROR 'Failed option: system edit'
+ message='Failed option: system edit'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed option: system edit'
Wed Apr  5 12:45:21 2023 - ERROR - Failed option: system edit
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_cobbler_system.sh line 46'
+ message='oe_test_cobbler_system.sh line 46'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_cobbler_system.sh line 46'
Wed Apr  5 12:45:22 2023 - ERROR - oe_test_cobbler_system.sh line 46
+ '[' 0 -eq 1 ']'
+ return 0
+ cobbler system list
+ grep OpenEuler
+ CHECK_RESULT 1 0 0 'Failed option: system list'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed option: system list'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed option: system list'
+ LOG_ERROR 'Failed option: system list'
+ message='Failed option: system list'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed option: system list'
Wed Apr  5 12:45:29 2023 - ERROR - Failed option: system list
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_cobbler_system.sh line 48'
+ message='oe_test_cobbler_system.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_cobbler_system.sh line 48'
Wed Apr  5 12:45:30 2023 - ERROR - oe_test_cobbler_system.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ cobbler system find
+ grep OpenEuler
+ CHECK_RESULT 1 0 0 'Failed option: system find'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed option: system find'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed option: system find'
+ LOG_ERROR 'Failed option: system find'
+ message='Failed option: system find'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed option: system find'
Wed Apr  5 12:45:37 2023 - ERROR - Failed option: system find
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_cobbler_system.sh line 50'
+ message='oe_test_cobbler_system.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_cobbler_system.sh line 50'
Wed Apr  5 12:45:38 2023 - ERROR - oe_test_cobbler_system.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ cobbler system remove --name=OpenEuler1
exception on server: 'internal error, unknown system name OpenEuler1'
+ CHECK_RESULT 0 0 0 'Failed option: system remove'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed option: system remove'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ cobbler system list
+ grep OpenEuler1
+ CHECK_RESULT 1 0 1 'Failed option: system remove'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='Failed option: system remove'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ cobbler system rename --name=OpenEuler2 --newname=OpenEuler3
exception on server: 'internal error, unknown system name OpenEuler2'
+ CHECK_RESULT 0 0 0 'Failed option: system rename'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed option: system rename'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ cobbler system list
+ grep OpenEuler3
+ CHECK_RESULT 1 0 0 'Failed option: system rename'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed option: system rename'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed option: system rename'
+ LOG_ERROR 'Failed option: system rename'
+ message='Failed option: system rename'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed option: system rename'
Wed Apr  5 12:46:02 2023 - ERROR - Failed option: system rename
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_cobbler_system.sh line 58'
+ message='oe_test_cobbler_system.sh line 58'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_cobbler_system.sh line 58'
Wed Apr  5 12:46:03 2023 - ERROR - oe_test_cobbler_system.sh line 58
+ '[' 0 -eq 1 ']'
+ return 0
+ cobbler system report --name=OpenEuler3
+ grep Name
+ CHECK_RESULT 1 0 0 'Failed option: system report'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Failed option: system report'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Failed option: system report'
+ LOG_ERROR 'Failed option: system report'
+ message='Failed option: system report'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed option: system report'
Wed Apr  5 12:46:10 2023 - ERROR - Failed option: system report
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_cobbler_system.sh line 60'
+ message='oe_test_cobbler_system.sh line 60'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_cobbler_system.sh line 60'
Wed Apr  5 12:46:11 2023 - ERROR - oe_test_cobbler_system.sh line 60
+ '[' 0 -eq 1 ']'
+ return 0
+ cobbler system get-autoinstall --name=OpenEuler3
# system not found
+ CHECK_RESULT 0 0 0 'Failed option: system get-autoinstall'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed option: system get-autoinstall'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ cobbler system poweroff --name=OpenEuler3
+ grep power
task started: 2023-04-05_124623_power
running python triggers from /var/lib/cobbler/triggers/task/power/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/power/pre/*
failed to execute power task on OpenEuler3, exception: 'internal error, unknown system name OpenEuler3'
+ CHECK_RESULT 0 0 0 'Failed option: system poweroff'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed option: system poweroff'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ cobbler system poweron --name=OpenEuler3
+ grep power
task started: 2023-04-05_124630_power
running python triggers from /var/lib/cobbler/triggers/task/power/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/power/pre/*
failed to execute power task on OpenEuler3, exception: 'internal error, unknown system name OpenEuler3'
+ CHECK_RESULT 0 0 0 'Failed option: system poweron'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed option: system poweron'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ cobbler system powerstatus --name=OpenEuler3
+ grep power
task started: 2023-04-05_124637_power
running python triggers from /var/lib/cobbler/triggers/task/power/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/power/pre/*
failed to execute power task on OpenEuler3, exception: 'internal error, unknown system name OpenEuler3'
+ CHECK_RESULT 0 0 0 'Failed option: system powerstatus'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed option: system powerstatus'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ cobbler system reboot --name=OpenEuler3
+ grep reboot
task started (id=Power management (reboot), time=Wed Apr  5 12:46:44 2023)
+ CHECK_RESULT 0 0 0 'Failed option: system reboot'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Failed option: system reboot'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End to run testcase.'
+ message='End to run testcase.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run testcase.'
Wed Apr  5 12:46:46 2023 - INFO  - End to run testcase.
+ CASE_RESULT 0
+ case_re=0
+ test -z 7
+ test 7 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Apr  5 12:46:47 2023 - ERROR - failed to execute the case.
+ exit 7
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Wed Apr  5 12:46:48 2023 - INFO  - Start to restore the test environment.
+ umount /dev/cdrom
umount: /dev/cdrom: no mount point specified.
+ systemctl stop httpd
+ systemctl stop cobblerd
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmp4l2l_diw ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmp4l2l_diw
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Wed Apr  5 12:47:55 2023 - INFO  - End to restore the test environment.
